[server]
musix_match_api_key = "ce0064c0705a30e2b136cfa78dd75eea"
http_proxy = "137.184.245.154:80"
https_proxy = "5.189.184.6:80"
use_full_lyrics = false
load_model = true
model_path = "C:\\Users\\Alex\\Downloads\\spotify-sentiment-analysis-bert-go-emotions-fine-tuned"